# Generated by Django 3.2.6 on 2021-08-27 12:06

from django.db import migrations, models

import trading.models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='order_type',
            field=models.PositiveSmallIntegerField(verbose_name=trading.models.Offer.OrderType),
        ),
    ]
