# Generated by Django 3.2.6 on 2021-08-30 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_alter_offer_order_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='order_type',
            field=models.IntegerField(choices=[(1, 'Buy'), (2, 'Sold')]),
        ),
    ]
